/*
 * Credits
 * The Credits API provides information about customer credit lines.
 *
 * OpenAPI spec version: 2.2.0
 * Contact: gipinacho@santander.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bancosantander.likeu.model;
/**
 * BenefitDetail
 */

public class BenefitDetail {
  /**
   * Indicates the status of the benefit.   * &#x60;INITIAL&#x60; -  Indicates the start of benefit.   * &#x60;EVALUATION&#x60; - Indicates when the benefit is in Evaluation.   * &#x60;FINAL&#x60; - Indicates the final phase of benefit. 
   */
/**
 * Adds 10 to the age
 * @param value - The age to add 10 to
 * @returns {value} - The age + 10
 */
  public enum StatusEnum {
    /**
	 * @param String
   * @param String
   * @param String
	 */
    INITIAL("INITIAL"),
    EVALUATION("EVALUATION"),
    FINAL("FINAL");

    private String value;
/**
	 * @param String
	 */
    StatusEnum(String value) {
      this.value = value;
    }

    /**
   * Indicates the key contract for the benefit
   * @return value
  **/
    public String getValue() {
      return value;
    }
  }


}
