/*
 * Credits
 * The Credits API provides information about customer credit lines.
 *
 * OpenAPI spec version: 2.2.0
 * Contact: gipinacho@santander.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bancosantander.likeu.model;

/**
 * CardDetail
 */

public class CardDetail {

	
	/**
	 * Indicates the status of the card. * &#x60;ACTIVE&#x60; - The card is in
	 * an active state and the customer can operate with it. *
	 * &#x60;BLOCKED&#x60; - The card is blocked and the customer cannot used
	 * it.
	 */



  /**
   * Indicates the status of the benefit.   * &#x60;INITIAL&#x60; -  Indicates the start of benefit.   * &#x60;EVALUATION&#x60; - Indicates when the benefit is in Evaluation.   * &#x60;FINAL&#x60; - Indicates the final phase of benefit. 
   * @param <currentLimit> ffff
   * @param <displayNumber>
   * @param <type>
   * @param <potentialLimit>
   */

	/**
	 * Adds 10 to the age
	 * 
	 * @param input
	 *            - The age to add 10 to
	 * @returns {number} - The age + 10
	 */
	public enum StatusEnum {
		ACTIVE("ACTIVE"), BLOCKED("BLOCKED");

		private String value;

		StatusEnum(String value) {
			this.value = value;
		}
		public String getValue() {
			return value;
		}

	}

}