package com.bancosantander.likeu.model;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class Data implements java.io.Serializable {

	private static final long serialVersionUID = 11L;


/**
 * Data
 * @param      contractkey    array that is the source of characters.
 * @param      activationdate   the initial offset.
 * @param      type    the length.
 * @param      status    the length.
 * @param      lastevaluationdate    the length.
 * @param      cutofdate    the length.
 * @param      card    the length.
 * @exception  IndexOutOfBoundsException  if the <code>offset</code>
 */

}