package com.bancosantander.likeu.model;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class Data implements java.io.Serializable {

	private static final long serialVersionUID = 11L;

	private java.lang.String contractkey;
	private java.lang.String activationdate;
	private java.lang.String type;
	private java.lang.String status;
	private java.lang.String lastevaluationdate;
	private java.lang.String cutofdate;
	private com.bancosantander.likeu.model.CardDetail card;

	public Data() {
	}
/**
 * Data
 * @param      contractkey    array that is the source of characters.
 * @param      activationdate   the initial offset.
 * @param      type    the length.
 * @param      status    the length.
 * @param      lastevaluationdate    the length.
 * @param      cutofdate    the length.
 * @param      card    the length.
 * @exception  IndexOutOfBoundsException  if the <code>offset</code>
 */
	public Data(java.lang.String contractkey, java.lang.String activationdate,
			java.lang.String type, java.lang.String status,
			java.lang.String lastevaluationdate, java.lang.String cutofdate,
			com.bancosantander.likeu.model.CardDetail card) {
		this.contractkey = contractkey;
		this.activationdate = activationdate;
		this.type = type;
		this.status = status;
		this.lastevaluationdate = lastevaluationdate;
		this.cutofdate = cutofdate;
		this.card = card;
	}
/**
   * Indicates the key contract for the benefit
   * @return value
  **/
	public java.lang.String getContractkey() {
		return this.contractkey;
	}
/**
	 * @param String
	 */
	public void setContractkey(java.lang.String contractkey) {
		this.contractkey = contractkey;
	}
/**
   * Indicates the key contract for the benefit
   * @return value
  **/
	public java.lang.String getActivationdate() {
		return this.activationdate;
	}
/**
	 * @param String
	 */
	public void setActivationdate(java.lang.String activationdate) {
		this.activationdate = activationdate;
	}
/**
   * Indicates the key contract for the benefit
   * @return value
  **/
	public java.lang.String getType() {
		return this.type;
	}
/**
	 * @param String
	 */
	public void setType(java.lang.String type) {
		this.type = type;
	}
/**
   * Indicates the key contract for the benefit
   * @return value
  **/
	public java.lang.String getStatus() {
		return this.status;
	}

/**
	 * @param String
	 */
	public void setStatus(java.lang.String status) {
		this.status = status;
	}
/**
   * Indicates the key contract for the benefit
   * @return value
  **/
	public java.lang.String getLastevaluationdate() {
		return this.lastevaluationdate;
	}
/**
	 * @param String
	 */
	public void setLastevaluationdate(java.lang.String lastevaluationdate) {
		this.lastevaluationdate = lastevaluationdate;
	}
/**
   * Indicates the key contract for the benefit
   * @return value
  **/
	public java.lang.String getCutofdate() {
		return this.cutofdate;
	}
/**
	 * @param String
	 */
	public void setCutofdate(java.lang.String cutofdate) {
		this.cutofdate = cutofdate;
	}
/**
   * Indicates the key contract for the benefit
   * @return value
  **/
	public com.bancosantander.likeu.model.CardDetail getCard() {
		return this.card;
	}
/**
	 * @param com.bancosantander.likeu.model.CardDetail
	 */
	public void setCard(com.bancosantander.likeu.model.CardDetail card) {
		this.card = card;
	}

}