package com.bancosantander.likeu.model;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class Data implements java.io.Serializable {

	private static final long serialVersionUID = 11L;

	public Data() {
	}
/**
 * Data
 * @param      contractkey    array that is the source of characters.
 * @param      activationdate   the initial offset.
 * @param      type    the length.
 * @param      status    the length.
 * @param      lastevaluationdate    the length.
 * @param      cutofdate    the length.
 * @param      card    the length.
 * @exception  IndexOutOfBoundsException  if the <code>offset</code>
 */
	public Data(java.lang.String contractkey, java.lang.String activationdate,
			java.lang.String type, java.lang.String status,
			java.lang.String lastevaluationdate, java.lang.String cutofdate,
			com.bancosantander.likeu.model.CardDetail card) {
		this.contractkey = contractkey;
		this.activationdate = activationdate;
		this.type = type;
		this.status = status;
		this.lastevaluationdate = lastevaluationdate;
		this.cutofdate = cutofdate;
		this.card = card;
	}
}