/*
 * Credits
 * The Credits API provides information about customer credit lines.
 *
 * OpenAPI spec version: 2.2.0
 * Contact: gipinacho@santander.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bancosantander.likeu.model;

/**
 * Retrieves the payment card total basic information 
 */
public class PaymentDetail {
/**
 * Retrieves the payment card basic information
 */
	public PaymentDetail() {
		//no code
	}
	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 * @param      amountPayment    array that is the source of characters.
	 * @param      minimumAmount    array that is the source of characters.
	 * @param      operationDate    array that is the source of characters.
	 */
	public PaymentDetail(java.lang.Integer amountPayment,
			java.lang.Integer minimumAmount, java.util.Date operationDate) {
		this.amountPayment = amountPayment;
		this.minimumAmount = minimumAmount;
		this.operationDate = new java.util.Date(operationDate.getTime());
	}

}
