/*
 * Credits
 * The Credits API provides information about customer credit lines.
 *
 * OpenAPI spec version: 2.2.0
 * Contact: gipinacho@santander.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bancosantander.likeu.model;

/**
 * Retrieves the payroll portability detail information for this period
 */
public class PayrollDetail {

  /**
   * Indicates the status of the payroll portability.   * &#x60;ACTIVE&#x60; -  Indicates that status for payroll portability is active in this moment.   * &#x60;INACTIVE&#x60; - Indicates that the payroll portability status is deactivated. 
   */
  public enum StatusEnum {
      /**
	 * @param String
   * @param String
	 */
    ACTIVE("ACTIVE"),
    INACTIVE("INACTIVE");

    private String value;
/**
	 * @param String
	 */
    StatusEnum(String value) {
      this.value = value;
    }
      /**
   * Indicates the key contract for the benefit
   * @return value
  **/
    public String getValue() {
      return value;
    }

  } 

}
