/*
 * Credits
 * The Credits API provides information about customer credit lines.
 *
 * OpenAPI spec version: 2.2.0
 * Contact: gipinacho@santander.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bancosantander.likeu.model;

import java.util.List;
/**
 * PeriodInfo
 */


public class PeriodInfo {

  private Integer currentPeriod = null;

  /**
   * Indicates the status of the period.   * &#x60;ACTIVE&#x60; -  Indicates that status for period is active in this moment.   * &#x60;INACTIVE&#x60; - Indicates that the period is inactive. 
   */

  private StatusEnum status = null;

  private List<PeriodDetail> periodDetail = null;

   /**
   * Indicates the current period number 
   * @return currentPeriod
  **/
  public Integer getCurrentPeriod() {
    return currentPeriod;
  }
/**
	 * @param Integer
	 */
  public void setCurrentPeriod(Integer currentPeriod) {
    this.currentPeriod = currentPeriod;
  }

   /**
   * Indicates the status of the period.   * &#x60;ACTIVE&#x60; -  Indicates that status for period is active in this moment.   * &#x60;INACTIVE&#x60; - Indicates that the period is inactive. 
   * @return status
  **/
  public StatusEnum getStatus() {
    return status;
  }
/**
	 * @param StatusEnum
	 */
  public void setStatus(StatusEnum status) {
    this.status = status;
  }

   /**
   * Card associated with the credit line.
   * @return periodDetail
  **/
  public List<PeriodDetail> getPeriodDetail() {
    return periodDetail;
  }
/**
	 * @param List<PeriodDetail>
	 */
  public void setPeriodDetail(List<PeriodDetail> periodDetail) {
    this.periodDetail = periodDetail;
  }
}
