/*
 * Credits
 * The Credits API provides information about customer credit lines.
 *
 * OpenAPI spec version: 2.2.0
 * Contact: gipinacho@santander.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.bancosantander.likeu.model;

/**
 * Retrieves the recurrent payment detail information
 */
public class RecurrentPaymentDetail {
  private String id = null;

  private StatusEnum status = null;

  private java.util.Date operationDate = null;

   /**
   * Indicates the reccurrent payment identifier.
   * @return id
  **/
  public String getId() {
    return id;
  }
/**
	 * @param String
	 */
  public void setId(String id) {
    this.id = id;
  }

   /**
   * Indicates the status of the recurrent payment.   * &#x60;ACTIVE&#x60; -  Indicates that status for recurrent payment is active in this moment.   * &#x60;INACTIVE&#x60; - Indicates that the recurrent payment status is inactive. 
   * @return status
  **/
  public StatusEnum getStatus() {
    return status;
  }
/**
	 * @param StatusEnum
	 */
  public void setStatus(StatusEnum status) {
    this.status = status;
  }

   /**
   * Indicates the date on which the recurrent payment was made. [ISO 8601] (https://www.iso.org/iso-8601-date-and-time-format.html
   * @return operationDate
  **/
  public java.util.Date getOperationDate() {
    if (operationDate != null) {
			return new java.util.Date(this.operationDate.getTime());
		  } else {
			return null;
		  }
  }
/**
	 * @param Date
	 */
  public void setOperationDate(java.util.Date operationDate) {
    if (operationDate != null) {
      this.operationDate = new java.util.Date(operationDate.getTime());
    } else {
        this.initoperationDateialDate = null;
    }
  }
}
